[versions]
exposed = "1.0.0-rc-4"
r2dbc-mariadb = "1.3.0"
r2dbc-pool = "1.0.2.RELEASE"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
r2dbc-mariadb = { module = "org.mariadb:r2dbc-mariadb", version.ref = "r2dbc-mariadb" }
r2dbc-pool = { module = "io.r2dbc:r2dbc-pool", version.ref = "r2dbc-pool" }


[bundles]
exposed = ["exposed-core", "exposed-r2dbc", "exposed-java-time", "exposed-json"]
databaseDriver = ["r2dbc-mariadb"]